### ISSUE TITLE
Price of the apps

### ISSUE THREAD

**Issue by jeremymaignan** [BigDataCorp/bigdata-pipeline-plugins#1]
Hi, 

I would like to know why some apps have a price of $0.0 on the database but the boolean IsFree is set at false. And when we look the price on the store the app is actually not free ?

Thanks

**Comment by MarcelloLins** [comment]
Hello @jeremymaignan , 

Do you mind sending the url of some examples like this so I can check ? 

Also, have in mind that you posted the issue on the wrong repository.
The "Play Store Crawler" repo is this one : github.com/MarcelloLins/GooglePlayAppsCrawler

Thanks for the input

**Comment by jeremymaignan** [comment]
Sure, the app with id 54b3bfe742a3ae078c3a4fc7 has a price of $0.0 and its boolean IsFree is set at false.

**Comment by jeremymaignan** [comment]
When I launch this query: db.getCollection('PlayStore_2015_02').find({IsFree : false, Price : 0.0}).count() the result is 135 159 and I suppose it should be 0.
